mod constants;
mod error;
mod models;
mod registry;
mod validation;

pub use constants::{
    API_ACCOUNTS_GET_BY_ID_V1, API_ACCOUNTS_GET_BY_IDENTITY_V1, API_ACCOUNTS_INTERNAL_BOOTSTRAP_V1, API_ACCOUNTS_UPDATE_V1, API_AUTH_GUEST_UPGRADE_V1,
    API_AUTH_LOGIN_V1, API_AUTH_REFRESH_V1, API_AUTH_REGISTER_V1, API_DISCOVERY_CATALOG_V1, API_DISCOVERY_DETAIL_V1, API_DISCOVERY_HOME_FEED_V1,
    API_DISCOVERY_PLAY_SESSION_GET_V1, API_DISCOVERY_PUBLISH_CREATE_V1, API_DISCOVERY_SCHEMA_V1, API_IDENTITY_POLICY_EVALUATION_V1,
    API_IDENTITY_PROFILE_GET_V1, API_IDENTITY_PROFILE_UPSERT_V1, AUTH_STACK_INTERNAL_API_CONTRACTS, ENV_WORLD_BUILDER_SERVICE_MESH_REGISTRY_JSON,
    ENV_WORLD_BUILDER_SERVICE_MESH_REGISTRY_PATH, MVP_ANON_2D_GATEWAY_API_CONTRACTS, MVP_ANON_2D_READ_API_CONTRACTS,
};
pub use error::MeshRegistryError;
pub use models::{
    PublishIngressHopRuntimeLimit, PublishIngressObservability, PublishIngressPolicy, PublishIngressRequiredHop, ResolvedServiceTarget,
    ServiceMeshRegistryDocument, ServiceRegistration,
};
pub use registry::ServiceMeshRegistry;

#[cfg(test)]
mod tests;
